[build]
builder = "nixpacks"

[deploy]
startCommand = "node server-railway.js"
healthcheckPath = "/api/health"
healthcheckInterval = 30
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1

[deploy.envs]
NODE_ENV = "production" 